
services:
  qt-socat:
    build: .
    image: out-qt-socat:latest
    container_name: qt-socat
    volumes:
      - "${PROJECT_PATH}:/src"
    stdin_open: true    
    tty: true
    command: bash
    restart: "no"

